name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  releases:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust: stable
            artifact_name: github-actions-playground
            asset_name: github-actions-playground_linux.zip
          - os: macOS-latest
            rust: stable
            artifact_name: github-actions-playground
            asset_name: github-actions-playground_osx.zip
          - os: windows-latest
            rust: stable
            artifact_name: github-actions-playground.exe
            asset_name: github-actions-playground_windows.zip
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build artifacts
        shell: bash
        run: |
          echo "Building the project"
          cargo build --release
          echo "Preparing the artifact"
          chmod +x "target/release/${{ matrix.artifact_name }}"
          gzip -h
          7z -h
          # zip -j "target/release/${{ matrix.artifact_name }}"
          # echo "moving target/release/${{ matrix.artifact_name }}.zip to ${{ matrix.asset_name }}"
          # mv "target/release/${{ matrix.artifact_name }}.zip" "${{ matrix.asset_name }}"
          ls -la
      # - name: Publishing to GitHub release
      #   uses: svenstaro/upload-release-action@v1-release
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: ${{ matrix.asset_name }}
      #     asset_name: ${{ matrix.asset_name }}
      #     tag: ${{ github.ref }}
